// libraries/react-design-system/src/components/MSkeleton.tsx
import React, { PropsWithChildren } from 'react';
import ContentLoader from 'react-content-loader';

export type Props = PropsWithChildren<{
  speed?: number;
  viewBox?: string;
  backgroundColor?: string;
  foregroundColor?: string;
}>;

export default function MSkeleton({
  speed = 2,
  viewBox,
  backgroundColor = '#f3f3f3',
  foregroundColor = '#ecebeb',
  children
}: Props) {
  return (
    <ContentLoader
      speed={speed}
      viewBox={viewBox}
      backgroundColor={backgroundColor}
      foregroundColor={foregroundColor}
    >
    { children }
  </ContentLoader>
  );
}

// libraries/angular-design-system/src/components/m-skeleton/m-skeleton.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'm-skeleton',
  templateUrl: './m-skeleton.component.html'
})
export class MSkeleton implements OnInit {
  @Input() viewBox!: string;
  @Input() speed?: number= 2;
  @Input() backgroundColor?: string = "#f3f3f3"
  @Input() foregroundColor?: string = "#ecebeb"

  constructor() { }

  ngOnInit(): void {
  }

}
<content-loader [viewBox]="viewBox" [backgroundColor]="backgroundColor" [foregroundColor]="foregroundColor"
  [speed]='speed'>
  <ng-content></ng-content>
</content-loader>
