// widgets/react-profile/src/App.tsx
import { MText, MButton, MAlert, MInput } from '@modyo/react-design-system';
import { useState } from 'react';

export default function App() {
  const [value, setValue] = useState('initial');
  return (
    <div>
      <h1>Hello</h1>
      <MText>world! from react</MText>
      <MButton
        text="click me!"
        onModButtonClick={() => (
          console.log('button-clicked')
        )}
      />
      <br />
      <MAlert
        header="the title"
        body="body prop text"
        actions={[
          { id: 'action 1', text: 'Action 1' },
          { id: 'action 2', text: 'Action 2' },
        ]}
        onModActionClick={({ detail: alertAction }) => (
          console.log('action-clicked', alertAction)
        )}
      >
        children text
      </MAlert>
      <br />
      <MInput
        id="input-1"
        placeholder="the placeholder"
        type="text"
        value={value}
        onModChange={({ detail }) => setValue(detail)}
      />
      <MText>
        the new value is: {value}
      </MText>
    </div>
  );
}

// widgets/angular-profile/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'title prop text';

  actions = [
    { id: 'action 1', text: 'Action 1' },
    { id: 'action 2', text: 'Action 2' }
  ];

  value = 'initial';

  onButtonClick() {
    console.log('button-clicked')
  }

  onActionClick(event: Event) {
    console.log('action-clicked', event)
  }

  onInputChange(event: Event) {
    this.value = (event as CustomEvent<string>).detail;
  }
}

<div>
  <h1>Hello</h1>
  <m-text>world! from vue</m-text>
  <m-button
    text="click me!"
    (modButtonClick)="onButtonClick()"
  >
  </m-button>
  <br />
  <m-alert
    [header]="title"
    body="body prop text"
    [actions]="actions"
    (modButtonClick)="onActionClick($event)"
  >
    children text
  </m-alert>
  <br />
  <m-input
    id="input-1"
    placeholder="the placeholder"
    type="text"
    [value]="value"
    (modChange)="onInputChange($event)"
  >
  </m-input>
  <m-text>
    the new value is: {{ value }}
  </m-text>
</div>
